# version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    command: ["/opt/venv/bin/poetry", "run", "uvicorn", "randomtrust.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: randomtrust
      POSTGRES_PASSWORD: randomtrust
      POSTGRES_DB: randomtrust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: randomtrust
      MINIO_ROOT_PASSWORD: randomtrustsecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
